{
  "isBase64Encoded": false,
  "statusCode": 400,
  "body": {
    "error": "Request failed due to server shutdown {\n  \"error\": {\n    \"message\": \"Request failed due to server shutdown\",\n    \"type\": \"server_error\",\n    \"param\": null,\n    \"code\": null\n  }\n}\n 500 {'error': {'message': 'Request failed due to server shutdown', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Wed, 18 Oct 2023 17:08:23 GMT', 'Content-Type': 'application/json', 'Content-Length': '141', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-model': 'gpt-4-turbo-0613', 'openai-organization': 'user-tl1wv9chydjidmopc8vig1gc', 'openai-processing-ms': '9581', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '3500', 'x-ratelimit-limit-tokens': '90000', 'x-ratelimit-remaining-requests': '3499', 'x-ratelimit-remaining-tokens': '89958', 'x-ratelimit-reset-requests': '17ms', 'x-ratelimit-reset-tokens': '28ms', 'x-request-id': '04b40821ae7ecb90639e00d2ff9ef17f', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '818261d3f9b2393d-IAD', 'alt-svc': 'h3=\":443\"; ma=86400'}",
    "description": "Traceback (most recent call last):\n  File \"/var/task/openai_text.py\", line 287, in handler\n    openai_results = openai.ChatCompletion.create(\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/task/openai/api_resources/chat_completion.py\", line 25, in create\n    return super().create(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/task/openai/api_resources/abstract/engine_api_resource.py\", line 155, in create\n    response, _, api_key = requester.request(\n                           ^^^^^^^^^^^^^^^^^^\n  File \"/var/task/openai/api_requestor.py\", line 299, in request\n    resp, got_stream = self._interpret_response(result, stream)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/var/task/openai/api_requestor.py\", line 710, in _interpret_response\n    self._interpret_response_line(\n  File \"/var/task/openai/api_requestor.py\", line 775, in _interpret_response_line\n    raise self.handle_error_response(\nopenai.error.APIError: Request failed due to server shutdown {\n  \"error\": {\n    \"message\": \"Request failed due to server shutdown\",\n    \"type\": \"server_error\",\n    \"param\": null,\n    \"code\": null\n  }\n}\n 500 {'error': {'message': 'Request failed due to server shutdown', 'type': 'server_error', 'param': None, 'code': None}} {'Date': 'Wed, 18 Oct 2023 17:08:23 GMT', 'Content-Type': 'application/json', 'Content-Length': '141', 'Connection': 'keep-alive', 'access-control-allow-origin': '*', 'openai-model': 'gpt-4-turbo-0613', 'openai-organization': 'user-tl1wv9chydjidmopc8vig1gc', 'openai-processing-ms': '9581', 'openai-version': '2020-10-01', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'x-ratelimit-limit-requests': '3500', 'x-ratelimit-limit-tokens': '90000', 'x-ratelimit-remaining-requests': '3499', 'x-ratelimit-remaining-tokens': '89958', 'x-ratelimit-reset-requests': '17ms', 'x-ratelimit-reset-tokens': '28ms', 'x-request-id': '04b40821ae7ecb90639e00d2ff9ef17f', 'CF-Cache-Status': 'DYNAMIC', 'Server': 'cloudflare', 'CF-RAY': '818261d3f9b2393d-IAD', 'alt-svc': 'h3=\":443\"; ma=86400'}\n"
  }
}
